const express=require('express')
const mainroute=require('./routes/main')
const app=express()
const cors=require('cors')
const mongoose=require('mongoose')
mongoose.connect('mongodb://127.0.0.1/mocktest')
app.use(cors())
app.use(express.json())
app.use('/',mainroute)
app.listen(4000,()=>console.log("4000"))